### Create category
POST localhost:8080/api/v1/category/admin/create
Content-Type:  application/json

{

  "uz": "Toshkent",
  "ru": "oblas",
  "eng": "Tash",
  "visible": true

}

### get all  category
GET localhost:8080/api/v1/category/admin/list

### update category
PUT localhost:8080/api/v1/category/admin/update/1
Content-Type:  application/json

{
  "uz": "qarshi",
  "ru": "oblas",
  "eng": "region",
  "visible": true

}


### delete category
DELETE localhost:8080/api/v1/category/admin/delete/1


### get by lang category
GET localhost:8080/api/v1/category/admin/byLang?lang=name_uz