### Create profle
POST localhost:8080/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3ODU1MzcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODI4NzE5MzcsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.gXax3lVFSQUE14GU8Kc0NZ-v6PQJpkwlX-5d9JSmTC-cKehMKhMbUK3Rf9gmhDiQLT4qGxFWcNkZjBt-4Q0rTg
Content-Type:  application/json

{
  "name": "moder1",
  "surname": "Valiyev",
  "email": "aaaa@gmail.com",
  "phone": "1213",
  "password": "123456",
  "role": "MODERATOR"
}